import Navbar from "../components/navbar/Navbar";
import "./globals.scss";
import classes from "./layout.module.scss";
import Header from "../components/header/Header";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classes.body}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
